// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/marinette/Documents/Work/Projects/ReactNative/expo/ExpoSandbox/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/marinette/Documents/Work/Projects/ReactNative/expo/ExpoSandbox/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('ExpoSandbox', appParameters);
});
require('/Users/marinette/Documents/Work/Projects/ReactNative/expo/ExpoSandbox/index.js');